
type Users {
    id : ID,
    username:String,
    email:String
}

type Household{
    id: ID,
    fullName:String,
    country:String,
    address:String ,
    JoinDate:String,
    TotalPoints: Float,
    recyclingEvents:[RecyclingEvent]
}

type RecyclingEvent{
    id:ID!,
    matType:MaterialType,
    WeightKG:Float ,
    recyclingDate:String,
    EcoPoints: Float,
    household:Household
}
type AuthPayload {
    token: String!
    role: String!
    householdId: Int
}

type Mutation{
    CreateHousehold(household: Householdinput!):Household,
    CalculateTotalPoints(id:Int!):Float,
    SavelogsForHouseholds:Boolean,
    CalculateTotalWeights(id:Int!):Float,
    addRecyclingEvent(dto:RecyclingEventinput!):RecyclingEvent,
    DeleteRecyclingEvent(id:Int!):Boolean,
    CalculateTotalEcoPoints(weight:Float!):Float,
    TotalCommunityWeight:Float
    login(username: String!, password: String!): AuthPayload
}
type Query{
    findAllRecyclingEventsByHouseholdId(id:Int!):[RecyclingEvent],
    HouseholdHaveHighestTotalPoints:Household
}



input Householdinput{
    username: String!
    password: String!
    email: String!
    fullName: String!
    country: String!
    address: String!
}
input RecyclingEventinput{
    matType:MaterialType,
    WeightKG:Float ,
    householdId:Int!,

}

enum MaterialType {
    PLASTIC, GLASS, METAL, PAPER
}
