spring.application.name=EcoPoints_Recycling_Tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/recycleapp
spring.datasource.username=reck
spring.datasource.password=reck123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.graphql.graphiql.enabled=true
# Generate a real random 256-bit+ secret for production ? don't ship this one.
jwt.secret=10nuq+Ami33aaZczJSOjs7rKH9+emBl8P
jwt.expiration-ms=86400000